package com.tpt.model.hibernate;
// default package
// Generated Dec 5, 2022, 10:49:34 PM by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DanhgiaId generated by hbm2java
 */
@Embeddable
public class DanhgiaId implements java.io.Serializable {

	private int idDg;
	private int idTk;
	private int idP;

	public DanhgiaId() {
	}

	public DanhgiaId(int idDg, int idTk, int idP) {
		this.idDg = idDg;
		this.idTk = idTk;
		this.idP = idP;
	}

	@Column(name = "id_dg", nullable = false)
	public int getIdDg() {
		return this.idDg;
	}

	public void setIdDg(int idDg) {
		this.idDg = idDg;
	}

	@Column(name = "id_tk", nullable = false)
	public int getIdTk() {
		return this.idTk;
	}

	public void setIdTk(int idTk) {
		this.idTk = idTk;
	}

	@Column(name = "id_p", nullable = false)
	public int getIdP() {
		return this.idP;
	}

	public void setIdP(int idP) {
		this.idP = idP;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DanhgiaId))
			return false;
		DanhgiaId castOther = (DanhgiaId) other;

		return (this.getIdDg() == castOther.getIdDg()) && (this.getIdTk() == castOther.getIdTk())
				&& (this.getIdP() == castOther.getIdP());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdDg();
		result = 37 * result + this.getIdTk();
		result = 37 * result + this.getIdP();
		return result;
	}

}
