package com.tpt.model.hibernate;

// default package
// Generated Dec 5, 2022, 10:49:34 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Danhgia generated by hbm2java
 */
@Entity
@Table(name = "danhgia", catalog = "timphong")
public class Danhgia implements java.io.Serializable {

	private DanhgiaId id;
	private Phong phong;
	private Taikhoan taikhoan;
	private Date ngay;
	private Float sosao;
	private String noidung;

	public Danhgia() {
	}

	public Danhgia(DanhgiaId id, Phong phong, Taikhoan taikhoan) {
		this.id = id;
		this.phong = phong;
		this.taikhoan = taikhoan;
	}

	public Danhgia(DanhgiaId id, Phong phong, Taikhoan taikhoan, Date ngay, Float sosao, String noidung) {
		this.id = id;
		this.phong = phong;
		this.taikhoan = taikhoan;
		this.ngay = ngay;
		this.sosao = sosao;
		this.noidung = noidung;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idDg", column = @Column(name = "id_dg", nullable = false)),
			@AttributeOverride(name = "idTk", column = @Column(name = "id_tk", nullable = false)),
			@AttributeOverride(name = "idP", column = @Column(name = "id_p", nullable = false)) })
	public DanhgiaId getId() {
		return this.id;
	}

	public void setId(DanhgiaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_p", nullable = false, insertable = false, updatable = false)
	public Phong getPhong() {
		return this.phong;
	}

	public void setPhong(Phong phong) {
		this.phong = phong;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tk", nullable = false, insertable = false, updatable = false)
	public Taikhoan getTaikhoan() {
		return this.taikhoan;
	}

	public void setTaikhoan(Taikhoan taikhoan) {
		this.taikhoan = taikhoan;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ngay", length = 10)
	public Date getNgay() {
		return this.ngay;
	}

	public void setNgay(Date ngay) {
		this.ngay = ngay;
	}

	@Column(name = "sosao", precision = 12, scale = 0)
	public Float getSosao() {
		return this.sosao;
	}

	public void setSosao(Float sosao) {
		this.sosao = sosao;
	}

	@Column(name = "noidung", length = 300)
	public String getNoidung() {
		return this.noidung;
	}

	public void setNoidung(String noidung) {
		this.noidung = noidung;
	}

}
