package com.tpt.model.hibernate;
// default package
// Generated Dec 5, 2022, 10:49:34 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Dathen generated by hbm2java
 */
@Entity
@Table(name = "dathen", catalog = "timphong")
public class Dathen implements java.io.Serializable {

	private DathenId id;
	private Phong phong;
	private Taikhoan taikhoan;
	private Integer trangthai;
	private Date ngay;
	private Date gio;

	public Dathen() {
	}

	public Dathen(DathenId id, Phong phong, Taikhoan taikhoan) {
		this.id = id;
		this.phong = phong;
		this.taikhoan = taikhoan;
	}

	public Dathen(DathenId id, Phong phong, Taikhoan taikhoan, Integer trangthai, Date ngay, Date gio) {
		this.id = id;
		this.phong = phong;
		this.taikhoan = taikhoan;
		this.trangthai = trangthai;
		this.ngay = ngay;
		this.gio = gio;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idDh", column = @Column(name = "id_dh", nullable = false)),
			@AttributeOverride(name = "idTk", column = @Column(name = "id_tk", nullable = false)),
			@AttributeOverride(name = "idP", column = @Column(name = "id_p", nullable = false)) })
	public DathenId getId() {
		return this.id;
	}

	public void setId(DathenId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_p", nullable = false, insertable = false, updatable = false)
	public Phong getPhong() {
		return this.phong;
	}

	public void setPhong(Phong phong) {
		this.phong = phong;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tk", nullable = false, insertable = false, updatable = false)
	public Taikhoan getTaikhoan() {
		return this.taikhoan;
	}

	public void setTaikhoan(Taikhoan taikhoan) {
		this.taikhoan = taikhoan;
	}

	@Column(name = "trangthai")
	public Integer getTrangthai() {
		return this.trangthai;
	}

	public void setTrangthai(Integer trangthai) {
		this.trangthai = trangthai;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ngay", length = 10)
	public Date getNgay() {
		return this.ngay;
	}

	public void setNgay(Date ngay) {
		this.ngay = ngay;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "gio", length = 8)
	public Date getGio() {
		return this.gio;
	}

	public void setGio(Date gio) {
		this.gio = gio;
	}

}
