package com.tpt.model.hibernate;
// default package
// Generated Dec 5, 2022, 10:49:34 PM by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DathenId generated by hbm2java
 */
@Embeddable
public class DathenId implements java.io.Serializable {

	private int idDh;
	private int idTk;
	private int idP;

	public DathenId() {
	}

	public DathenId(int idDh, int idTk, int idP) {
		this.idDh = idDh;
		this.idTk = idTk;
		this.idP = idP;
	}

	@Column(name = "id_dh", nullable = false)
	public int getIdDh() {
		return this.idDh;
	}

	public void setIdDh(int idDh) {
		this.idDh = idDh;
	}

	@Column(name = "id_tk", nullable = false)
	public int getIdTk() {
		return this.idTk;
	}

	public void setIdTk(int idTk) {
		this.idTk = idTk;
	}

	@Column(name = "id_p", nullable = false)
	public int getIdP() {
		return this.idP;
	}

	public void setIdP(int idP) {
		this.idP = idP;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DathenId))
			return false;
		DathenId castOther = (DathenId) other;

		return (this.getIdDh() == castOther.getIdDh()) && (this.getIdTk() == castOther.getIdTk())
				&& (this.getIdP() == castOther.getIdP());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdDh();
		result = 37 * result + this.getIdTk();
		result = 37 * result + this.getIdP();
		return result;
	}

}
