package com.tpt.model.hibernate;
// default package
// Generated Dec 5, 2022, 10:49:34 PM by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Hinhanh generated by hbm2java
 */
@Entity
@Table(name = "hinhanh", catalog = "timphong")
public class Hinhanh implements java.io.Serializable {

	private HinhanhId id;
	private Phong phong;

	public Hinhanh() {
	}

	public Hinhanh(HinhanhId id, Phong phong) {
		this.id = id;
		this.phong = phong;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "stt", column = @Column(name = "stt", nullable = false)),
			@AttributeOverride(name = "idP", column = @Column(name = "id_p", nullable = false)),
			@AttributeOverride(name = "hinhanh", column = @Column(name = "hinhanh", nullable = false, length = 100)) })
	public HinhanhId getId() {
		return this.id;
	}

	public void setId(HinhanhId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_p", nullable = false, insertable = false, updatable = false)
	public Phong getPhong() {
		return this.phong;
	}

	public void setPhong(Phong phong) {
		this.phong = phong;
	}

}
