package com.tpt.model.hibernate;
// default package
// Generated Dec 5, 2022, 10:49:34 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Loaiphong generated by hbm2java
 */
@Entity
@Table(name = "loaiphong", catalog = "timphong")
public class Loaiphong implements java.io.Serializable {

	private Integer idLp;
	private String tenloai;
	private Set<Phong> phongs = new HashSet<Phong>(0);

	public Loaiphong() {
	}

	public Loaiphong(String tenloai) {
		this.tenloai = tenloai;
	}

	public Loaiphong(String tenloai, Set<Phong> phongs) {
		this.tenloai = tenloai;
		this.phongs = phongs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_lp", unique = true, nullable = false)
	public Integer getIdLp() {
		return this.idLp;
	}

	public void setIdLp(Integer idLp) {
		this.idLp = idLp;
	}

	@Column(name = "tenloai", nullable = false, length = 30)
	public String getTenloai() {
		return this.tenloai;
	}

	public void setTenloai(String tenloai) {
		this.tenloai = tenloai;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "loaiphong")
	public Set<Phong> getPhongs() {
		return this.phongs;
	}

	public void setPhongs(Set<Phong> phongs) {
		this.phongs = phongs;
	}

}
