package com.tpt.model.hibernate;
// default package
// Generated Dec 5, 2022, 10:49:34 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Phong generated by hbm2java
 */
@Entity
@Table(name = "phong", catalog = "timphong", uniqueConstraints = @UniqueConstraint(columnNames = "anhchinh"))
public class Phong implements java.io.Serializable {

	private Integer idP;
	private Loaiphong loaiphong;
	private Taikhoan taikhoan;
	private Xaphuong xaphuong;
	private String ten;
	private String anhchinh;
	private int trangthai;
	private float chieudai;
	private float chieurong;
	private int gia;
	private Integer songuoi;
	private String dcchitiet;
	private String mota;
	private Date ngaydang;
	private Set<Dathen> dathens = new HashSet<Dathen>(0);
	private Set<Danhgia> danhgias = new HashSet<Danhgia>(0);
	private Set<Hinhanh> hinhanhs = new HashSet<Hinhanh>(0);

	public Phong() {
	}

	public Phong(String ten, int trangthai, float chieudai, float chieurong, int gia, String dcchitiet) {
		this.ten = ten;
		this.trangthai = trangthai;
		this.chieudai = chieudai;
		this.chieurong = chieurong;
		this.gia = gia;
		this.dcchitiet = dcchitiet;
	}

	public Phong(Loaiphong loaiphong, Taikhoan taikhoan, Xaphuong xaphuong, String ten, String anhchinh, int trangthai,
			float chieudai, float chieurong, int gia, Integer songuoi, String dcchitiet, String mota, Date ngaydang,
			Set<Dathen> dathens, Set<Danhgia> danhgias, Set<Hinhanh> hinhanhs) {
		this.loaiphong = loaiphong;
		this.taikhoan = taikhoan;
		this.xaphuong = xaphuong;
		this.ten = ten;
		this.anhchinh = anhchinh;
		this.trangthai = trangthai;
		this.chieudai = chieudai;
		this.chieurong = chieurong;
		this.gia = gia;
		this.songuoi = songuoi;
		this.dcchitiet = dcchitiet;
		this.mota = mota;
		this.ngaydang = ngaydang;
		this.dathens = dathens;
		this.danhgias = danhgias;
		this.hinhanhs = hinhanhs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_p", unique = true, nullable = false)
	public Integer getIdP() {
		return this.idP;
	}

	public void setIdP(Integer idP) {
		this.idP = idP;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_lp")
	public Loaiphong getLoaiphong() {
		return this.loaiphong;
	}

	public void setLoaiphong(Loaiphong loaiphong) {
		this.loaiphong = loaiphong;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_tk")
	public Taikhoan getTaikhoan() {
		return this.taikhoan;
	}

	public void setTaikhoan(Taikhoan taikhoan) {
		this.taikhoan = taikhoan;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_x")
	public Xaphuong getXaphuong() {
		return this.xaphuong;
	}

	public void setXaphuong(Xaphuong xaphuong) {
		this.xaphuong = xaphuong;
	}

	@Column(name = "ten", nullable = false, length = 100)
	public String getTen() {
		return this.ten;
	}

	public void setTen(String ten) {
		this.ten = ten;
	}

	@Column(name = "anhchinh", unique = true, length = 100)
	public String getAnhchinh() {
		return this.anhchinh;
	}

	public void setAnhchinh(String anhchinh) {
		this.anhchinh = anhchinh;
	}

	@Column(name = "trangthai", nullable = false)
	public int getTrangthai() {
		return this.trangthai;
	}

	public void setTrangthai(int trangthai) {
		this.trangthai = trangthai;
	}

	@Column(name = "chieudai", nullable = false, precision = 12, scale = 0)
	public float getChieudai() {
		return this.chieudai;
	}

	public void setChieudai(float chieudai) {
		this.chieudai = chieudai;
	}

	@Column(name = "chieurong", nullable = false, precision = 12, scale = 0)
	public float getChieurong() {
		return this.chieurong;
	}

	public void setChieurong(float chieurong) {
		this.chieurong = chieurong;
	}

	@Column(name = "gia", nullable = false)
	public int getGia() {
		return this.gia;
	}

	public void setGia(int gia) {
		this.gia = gia;
	}

	@Column(name = "songuoi")
	public Integer getSonguoi() {
		return this.songuoi;
	}

	public void setSonguoi(Integer songuoi) {
		this.songuoi = songuoi;
	}

	@Column(name = "dcchitiet", nullable = false, length = 100)
	public String getDcchitiet() {
		return this.dcchitiet;
	}

	public void setDcchitiet(String dcchitiet) {
		this.dcchitiet = dcchitiet;
	}

	@Column(name = "mota", length = 500)
	public String getMota() {
		return this.mota;
	}

	public void setMota(String mota) {
		this.mota = mota;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ngaydang", length = 10)
	public Date getNgaydang() {
		return this.ngaydang;
	}

	public void setNgaydang(Date ngaydang) {
		this.ngaydang = ngaydang;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "phong")
	public Set<Dathen> getDathens() {
		return this.dathens;
	}

	public void setDathens(Set<Dathen> dathens) {
		this.dathens = dathens;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "phong")
	public Set<Danhgia> getDanhgias() {
		return this.danhgias;
	}

	public void setDanhgias(Set<Danhgia> danhgias) {
		this.danhgias = danhgias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "phong")
	public Set<Hinhanh> getHinhanhs() {
		return this.hinhanhs;
	}

	public void setHinhanhs(Set<Hinhanh> hinhanhs) {
		this.hinhanhs = hinhanhs;
	}

}
