package com.tpt.model.hibernate;
// default package
// Generated Dec 5, 2022, 10:49:34 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Quocgia generated by hbm2java
 */
@Entity
@Table(name = "quocgia", catalog = "timphong")
public class Quocgia implements java.io.Serializable {

	private Long id;
	private String tenQuocGia;
	private Set<Tinhthanhpho> tinhthanhphos = new HashSet<Tinhthanhpho>(0);

	public Quocgia() {
	}

	public Quocgia(String tenQuocGia) {
		this.tenQuocGia = tenQuocGia;
	}

	public Quocgia(String tenQuocGia, Set<Tinhthanhpho> tinhthanhphos) {
		this.tenQuocGia = tenQuocGia;
		this.tinhthanhphos = tinhthanhphos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "tenQuocGia", nullable = false, length = 200)
	public String getTenQuocGia() {
		return this.tenQuocGia;
	}

	public void setTenQuocGia(String tenQuocGia) {
		this.tenQuocGia = tenQuocGia;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "quocgia")
	public Set<Tinhthanhpho> getTinhthanhphos() {
		return this.tinhthanhphos;
	}

	public void setTinhthanhphos(Set<Tinhthanhpho> tinhthanhphos) {
		this.tinhthanhphos = tinhthanhphos;
	}

}
