// default package
// Generated Dec 5, 2022, 10:49:34 PM by Hibernate Tools 4.3.6.Final
package com.tpt.model.hibernate;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Taikhoan generated by hbm2java
 */
@Entity
@Table(name = "taikhoan", catalog = "timphong", uniqueConstraints = { @UniqueConstraint(columnNames = "email"),
		@UniqueConstraint(columnNames = "sdt"), @UniqueConstraint(columnNames = "tentk") })
public class Taikhoan implements java.io.Serializable {

	private Integer idTk;
	private String tentk;
	private String matkhau;
	private int quyen;
	private String email;
	private String sdt;
	private String ho;
	private String ten;
	private String anhdaidien;
	private Set<Dathen> dathens = new HashSet<Dathen>(0);
	private Set<Phong> phongs = new HashSet<Phong>(0);
	private Set<Danhgia> danhgias = new HashSet<Danhgia>(0);

	public Taikhoan() {
	}

	public Taikhoan(String tentk, String matkhau, int quyen, String email, String sdt, String ho, String ten) {
		this.tentk = tentk;
		this.matkhau = matkhau;
		this.quyen = quyen;
		this.email = email;
		this.sdt = sdt;
		this.ho = ho;
		this.ten = ten;
	}

	public Taikhoan(String tentk, String matkhau, int quyen, String email, String sdt, String ho, String ten,
			String anhdaidien, Set<Dathen> dathens, Set<Phong> phongs, Set<Danhgia> danhgias) {
		this.tentk = tentk;
		this.matkhau = matkhau;
		this.quyen = quyen;
		this.email = email;
		this.sdt = sdt;
		this.ho = ho;
		this.ten = ten;
		this.anhdaidien = anhdaidien;
		this.dathens = dathens;
		this.phongs = phongs;
		this.danhgias = danhgias;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_tk", unique = true, nullable = false)
	public Integer getIdTk() {
		return this.idTk;
	}

	public void setIdTk(Integer idTk) {
		this.idTk = idTk;
	}

	@Column(name = "tentk", unique = true, nullable = false, length = 30)
	public String getTentk() {
		return this.tentk;
	}

	public void setTentk(String tentk) {
		this.tentk = tentk;
	}

	@Column(name = "matkhau", nullable = false, length = 30)
	public String getMatkhau() {
		return this.matkhau;
	}

	public void setMatkhau(String matkhau) {
		this.matkhau = matkhau;
	}

	@Column(name = "quyen", nullable = false)
	public int getQuyen() {
		return this.quyen;
	}

	public void setQuyen(int quyen) {
		this.quyen = quyen;
	}

	@Column(name = "email", unique = true, nullable = false, length = 40)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "sdt", unique = true, nullable = false, length = 10)
	public String getSdt() {
		return this.sdt;
	}

	public void setSdt(String sdt) {
		this.sdt = sdt;
	}

	@Column(name = "ho", nullable = false, length = 10)
	public String getHo() {
		return this.ho;
	}

	public void setHo(String ho) {
		this.ho = ho;
	}

	@Column(name = "ten", nullable = false, length = 30)
	public String getTen() {
		return this.ten;
	}

	public void setTen(String ten) {
		this.ten = ten;
	}

	@Column(name = "anhdaidien", length = 100)
	public String getAnhdaidien() {
		return this.anhdaidien;
	}

	public void setAnhdaidien(String anhdaidien) {
		this.anhdaidien = anhdaidien;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "taikhoan")
	public Set<Dathen> getDathens() {
		return this.dathens;
	}

	public void setDathens(Set<Dathen> dathens) {
		this.dathens = dathens;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "taikhoan")
	public Set<Phong> getPhongs() {
		return this.phongs;
	}

	public void setPhongs(Set<Phong> phongs) {
		this.phongs = phongs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "taikhoan")
	public Set<Danhgia> getDanhgias() {
		return this.danhgias;
	}

	public void setDanhgias(Set<Danhgia> danhgias) {
		this.danhgias = danhgias;
	}

}
