package com.tpt.model.hibernate;
// default package
// Generated Dec 5, 2022, 10:49:34 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Xaphuong generated by hbm2java
 */
@Entity
@Table(name = "xaphuong", catalog = "timphong")
public class Xaphuong implements java.io.Serializable {

	private Long id;
	private Quanhuyen quanhuyen;
	private String tenXaPhuong;
	private Set<Phong> phongs = new HashSet<Phong>(0);

	public Xaphuong() {
	}

	public Xaphuong(Quanhuyen quanhuyen, String tenXaPhuong) {
		this.quanhuyen = quanhuyen;
		this.tenXaPhuong = tenXaPhuong;
	}

	public Xaphuong(Quanhuyen quanhuyen, String tenXaPhuong, Set<Phong> phongs) {
		this.quanhuyen = quanhuyen;
		this.tenXaPhuong = tenXaPhuong;
		this.phongs = phongs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "quanHuyenId", nullable = false)
	public Quanhuyen getQuanhuyen() {
		return this.quanhuyen;
	}

	public void setQuanhuyen(Quanhuyen quanhuyen) {
		this.quanhuyen = quanhuyen;
	}

	@Column(name = "tenXaPhuong", nullable = false, length = 200)
	public String getTenXaPhuong() {
		return this.tenXaPhuong;
	}

	public void setTenXaPhuong(String tenXaPhuong) {
		this.tenXaPhuong = tenXaPhuong;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "xaphuong")
	public Set<Phong> getPhongs() {
		return this.phongs;
	}

	public void setPhongs(Set<Phong> phongs) {
		this.phongs = phongs;
	}

}
